name: Unit Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: yarn package
      - run: yarn test
